server:
  port: 8888
  
security:
  basic:
    enabled: true
  user:
    name: config-server
    password: config-server
    
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/esm-services/esm-config-repo
  profiles:
    active:
    - prod
  application:
    name: config-server
    
logging:
  level:
    root: INFO 
    org.springframework.web: INFO
    org.springframework.cloud.sleuth: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /logs/config-server/config-server.log